# Site settings
title: Hyuwah Github Page
description: > # this means to ignore newlines until "baseurl:"
  A website for showcasing hyuwah's creation.
baseurl: "" # the subpath of your site, e.g. /blog/
# url: "http://hyuwah.github.io" # the base hostname & protocol for your site you most probably don't need to set it
url: "http://yourdomain.com"
# Build settings
markdown: kramdown
paginate: 5 # pagination based on number of posts
#paginate_path: "page/:num"
paginate_path: "/blog/page/:num"
highlighter: rouge

logo: Github-<b>Hyuwah</b>
mainimg: https://snap-photos.s3.amazonaws.com/img-thumbs/960w/CWYK8CLC61.jpg

owner:
    email: muhammad.whydn@gmail.com
    facebook:
        show: true
        name: "Muhammad Wahyudin"
        url: "https://fb.me/hyuwah"
    github:
        show: true
        username: "hyuwah"
    twitter:
        show: false
        username: ""
    disqus:
        show: true
        username: "hyuwah"
sass:
    sass_dir: _sass
    style: compressed
permalink: "/blog/:title"
gems:
    - jekyll-paginate
    - jekyll-feed

collections:
  - projects
