# Site settings
title: "Hyuwah Github Page"
description: > # this means to ignore newlines until "baseurl:"
  "A website for showcasing hyuwah's creation."
baseurl: "/" # the subpath of your site, e.g. /blog/
# url: "http://hyuwah.github.io" # the base hostname & protocol for your site you most probably don't need to set it

# Build settings
markdown: kramdown
paginate: 5 # pagination based on number of posts
paginate_path: "page/:num"
highlighter: pygments
gems: [jekyll-paginate]

# comments
disqus: hyuwah # add disqus shortname here

# author info
# add your appropriate info here
avatar_image: avatar_square.jpg # Avatar image in assets/image/FILE_NAME.*
author: "Muhammad Wahyudin" # your name
bio: "Undergraduate in Electronic and Instrumentation Physics, Enthusiastic with all things related to codes"
email: "muhammad.whydn@gmail.com"
email_md5: "0574d85d4c36302ec44030dd926b26c6" # md5 hash of your email
twitter_username: "hyuwah"
github_username: "hyuwah"
google_username: "MuhammadWahyudin31" # plus.google.com/+USERNAME

# Theming options
# These settings are mandatory.
theme:              'indigo-red'
# drawer theming
drawer:
  text_color:       'grey-600'
  header_color:     'blue-500'
  navigation_color: 'grey-200'
# footer theming
footer:
  text_color: 'blue-grey-200'
  color: 'blue-grey-600'
