# Site settings
title: Muhammad Wahyudin's Page
description: > # this means to ignore newlines until "baseurl:"
  A website for showcasing hyuwah's creation.
baseurl: "" # the subpath of your site, e.g. /blog/
# url: "http://hyuwah.github.io" # the base hostname & protocol for your site you most probably don't need to set it
url: "http://hyuwah.me"

# Site Variables
logo: <img  src="/assets/favicon/favicon-96x96.png" width="24" style="vertical-align:middle;"> hyuwah<b>.me</b>
#image used on frontpage parallax
mainimg:
  top: assets/images/mainparalax.jpg
  bottom: assets/images/mainparalax.jpg

owner:
    name: "Muhammad Wahyudin"
    taglines: "Coding Lover - Instrumentation & Electronics Physicist - Technology Enthusiast"
    shortdesc: > # Ignore newlines until next Variables
      <p>Hi, Saya mahasiswa tingkat akhir S1 Fisika Universitas Padjadjaran dari Purwakarta, Indonesia.<br> 2 tahun sudah saya berkecimpung di dunia coding. Mulai dari komputasi fisika dengan Matlab hingga programming mikrokontroler untuk sistem instrumentasi dengan C bahkan Assembly. Saya pun sangat tertarik dengan hal berbau teknologi.<br> Disamping mengerjakan tugas akhir yang berjudul <em>"Perancangan Sistem Pengukuran Zeta Potensial dengan Metode Potensial Sedimentasi"</em>, saya juga menekuni dunia front-end web development melalui situs ini, sub halaman skripsi, dan beberapa proyek lainnya. </p>.
    email: muhammad.whydn@gmail.com
    facebook:
        show: true
        name: "Muhammad Wahyudin"
        url: "https://fb.me/hyuwah"
    github:
        show: true
        username: "hyuwah"
        url: "https://github.com/hyuwah/hyuwah.github.io"
    twitter:
        show: true
        username: "hyuwah"
    disqus:
        show: true
        username: "hyuwah"
    gplus:
        show: false
        url: ""
    codepen:
        show: true
        username: "hyuwah"
    linkedin:
        show: true
        url: "https://id.linkedin.com/in/hyuwah"

# Build settings
markdown: kramdown
paginate: 5 # pagination based on number of posts
paginate_path: "/blog/page/:num"
highlighter: rouge
sass:
    sass_dir: _sass
    style: compressed
permalink: "/blog/:title/"
gems:
    - jekyll-paginate
    - jekyll-feed

# Collections
collections:
  - projects
  - timelines

exclude: ["Gemfile",
          "Gemfile.lock",
          "gulpfile.js",
          "node_modules",
          "package.json"]
