# Site settings
title: Muhammad Wahyudin's Page
description: > # this means to ignore newlines until "baseurl:"
  A website to showcase the work of Muhammad Wahyudin.
baseurl: "" # the subpath of your site, e.g. /blog/
# url: "http://hyuwah.github.io" # the base hostname & protocol for your site you most probably don't need to set it
url: "http://hyuwah.github.io"

# Site Variables
#logo: <img  src="/assets/favicon/favicon-96x96.png" width="24" style="vertical-align:middle;"> hyuwah<b>.github</b>.io
logo: <img  src="/assets/images/logo.png" width="48" style="vertical-align:middle;"> <b>.github</b>.io

#image used on frontpage parallax
mainimg:
  top: assets/images/pexels-photo.webp
  bottom: assets/images/arduino.webp

owner:
    name: "MUHAMMAD WAHYUDIN"
    taglines: "Software Developer - Instrumentation & Electronics Physicist - Technology Enthusiast"
    email: muhammad.whydn@gmail.com
    facebook:
        show: false
        name: "Muhammad Wahyudin"
        url: "https://fb.me/hyuwah"
    github:
        show: true
        username: "hyuwah"
        url: "https://github.com/hyuwah/hyuwah.github.io"
    twitter:
        show: true
        username: "hyuwah"
    disqus:
        show: true
        username: "hyuwah"
    gplus:
        show: false
        url: ""
    codepen:
        show: true
        username: "hyuwah"
    gitlab:
        show: true
        username: "hyuwah"
    linkedin:
        show: true
        url: "https://id.linkedin.com/in/hyuwah"

# Build settings
markdown: kramdown
paginate: 5 # pagination based on number of posts
paginate_path: "/blog/page/:num"
highlighter: rouge
kramdown:
  input:          GFM
  # https://github.com/jekyll/jekyll/pull/4090
  syntax_highlighter: rouge

  # Rouge Highlighter in Kramdown › http://kramdown.gettalong.org/syntax_highlighter/rouge.html
  # span, block element options fall back to global
  syntax_highlighter_opts:
    # Rouge Options › https://github.com/jneen/rouge#full-options
    css_class: 'highlight'
    #line_numbers: true # bad idea, spans don't need linenos and would inherit this option

cloudinary:
  cloud_name: hyuwah-github-io
  verbose: true

sass:
    sass_dir: _sass
    style: compressed
permalink: "/blog/:year/:month/:title/"
plugins:
    - jekyll-paginate
    - jekyll-feed

# Collections
collections:
  - projects
  - timelines

exclude: ["Gemfile",
          "Gemfile.lock",
          "gulpfile.js",
          "node_modules",
          "package.json"]
