# Site settings
title: Hyuwah Github Page
description: > # this means to ignore newlines until "baseurl:"
  A website for showcasing hyuwah's creation.
baseurl: "" # the subpath of your site, e.g. /blog/
# url: "http://hyuwah.github.io" # the base hostname & protocol for your site you most probably don't need to set it
url: "http://yourdomain.com"

# Site Variables
logo: Github-<b>Hyuwah</b>
#image used on frontpage parallax
mainimg:
  top: https://snap-photos.s3.amazonaws.com/img-thumbs/960w/CWYK8CLC61.jpg
  bottom: https://snap-photos.s3.amazonaws.com/img-thumbs/960w/CWYK8CLC61.jpg

owner:
    name: "Muhammad Wahyudin"
    taglines: "Coding Lover - Instrumentation & Electronics Physics - Technology Enthusiast"
    shortdesc: > # Ignore newlines until next Variables
      Hi, Saya mahasiswa S1 Fisika Universitas Padjadjaran dari Purwakarta, Indonesia. 2 tahun sudah saya berkecimpung di dunia coding. Mulai dari fisika komputasi dengan Matlab hingga programming mikrokontroler untuk sistem instrumentasi dengan C bahkan Assembly. Disamping itu, saya sangat tertarik dengan hal berbau teknologi, terlebih dunia front-end web development.
    email: muhammad.whydn@gmail.com
    facebook:
        show: true
        name: "Muhammad Wahyudin"
        url: "https://fb.me/hyuwah"
    github:
        show: true
        username: "hyuwah"
        url: "https://github.com/hyuwah/hyuwah.github.io"
    twitter:
        show: true
        username: "hyuwah"
    disqus:
        show: true
        username: "hyuwah"
    gplus:
        show: false
        url: ""
    codepen:
        show: true
        username: "hyuwah"
    linkedin:
        show: true
        url: "https://id.linkedin.com/in/hyuwah"

# Build settings
markdown: kramdown
paginate: 5 # pagination based on number of posts
paginate_path: "/blog/page/:num"
highlighter: rouge
sass:
    sass_dir: _sass
    style: compressed
permalink: "/blog/:title"
gems:
    - jekyll-paginate
    - jekyll-feed

# Collections
collections:
  - projects
  - timelines
